### ISSUE TITLE
Contributor Guidelines

### ISSUE THREAD

**Issue by stephwright** [stephwright/Brain#2]
- [x] Review https://help.github.com/articles/setting-guidelines-for-repository-contributors/
- [x] Put draft of guidelines into clean etherpad
- [x] Submit for review by MSL
- [x] Refine and send out for review to Study Groups asking for feedback
- [ ] Incorporate feedback
- [ ] Discuss w/ @auremoser and @kaythaney for next steps

**Comment by stephwright** [comment]
https://public.etherpad-mozilla.org/p/SGContributorGuidelines
Also repo: https://github.com/stephwright/studyGroup/blob/gh-pages/CONTRIBUTION.md

**Comment by auremoser** [comment]
Very cool! I am new so I'm not sure if this is relevant, but would we be building the guidlines into this format? We list it on the Training part of the site, I only know because I'm doing the content inventory now, and there's already a pseudo-relevant lesson on [Code Review](http://mozillascience.github.io/codeReview/intro.html) and another on [Usability Testing](http://mozillascience.github.io/lessons/userTesting/index.html). 
- Or maybe this will just be a template for Study Group Contributions? 
- Or maybe it will be like Abby's GitBook guide on Working Open? 

It's o.k. if I'm totally off but I just want ot know what format we're endorsing for these materials moving forward. Thanks for tagging me though, super cool!

**Comment by stephwright** [comment]
You know... we've had a conversation (at least I think we did, or it's my imagination because I can't find my notes on it right now) about who the audience was for this.  Was this supposed to be Contribution Guidelines for the Study Groups repo?  Or was it supposed to be Contribution Guidelines to be included in the Study Group repo to be used by study group leads as they developed their  own repos.  Based on our conversation with the study group leads on the last call, I believe it's the latter so it's just a template for Study Group contributions.  I think we probably should create something to be included in Abby's guide on how to work open though.   It's part of good practice, right?

What do you all think?

**Comment by auremoser** [comment]
I'm down for whatever you'd like or you think is appropriate based on your (probably better) memory of the call! It would be cool to get things in a similar format too though, so I like the Guide inclusion idea. :)
